#!/usr/bin/env python
import os

from maia.utils            import parse_yaml_cgns
from maia.utils.test_utils import mesh_dir
from maia.io               import cgns_io_tree as IOT

# TODO merge with test/conftest.py/generate_cgns_files
for full_mesh_name in os.listdir(mesh_dir):
  mesh_name, extension = os.path.splitext(full_mesh_name)
  if (extension==".yaml"):
    with open(os.path.join(mesh_dir,full_mesh_name)) as yt:
      t = parse_yaml_cgns.to_cgns_tree(yt)
      IOT.write_tree(t,mesh_name+".cgns")
