#!/usr/bin/env python

import argparse
from pathlib import Path
import os

import maia
import Converter.PyTree as C

parser = argparse.ArgumentParser(description='Convert a NGon/NFace mesh from old to new CGNS convention')
parser.add_argument('inputs', metavar='IN', type=Path, help='input files', nargs='+')
args = parser.parse_args()

for input in args.inputs:
  base_name,extension = os.path.splitext(input)
  t = C.convertFile2PyTree(str(input))
  maia.algo.ngon_old_to_new(t)
  C.convertPyTree2File(t,base_name+'_new'+extension)
