#!/usr/bin/env python3

import argparse
from pathlib import Path
import os

import maia

parser = argparse.ArgumentParser(description='Convert a NGon/NFace mesh from old to new CGNS convention')
parser.add_argument('inputs', metavar='IN', type=Path, help='input files', nargs='+')
args = parser.parse_args()

for input in args.inputs:
  base_name,extension = os.path.splitext(input)
  t = maia.io.read_tree(str(input))
  maia.algo.seq.poly_old_to_new(t)
  maia.io.write_tree(t,base_name+'_new'+extension)
