#!/usr/bin/env python

import argparse
from pathlib import Path

from maia.utils import parse_yaml_cgns,parse_cgns_yaml, script_utils
import os
import Converter.PyTree as C

parser = argparse.ArgumentParser(description='Convert between a YAML/CGNS and HDF5/CGNS')
parser.add_argument('input', metavar='IN', type=Path, help='input file')
parser.add_argument('-o','--output', metavar='OUT', type=Path, help='output file')

args = parser.parse_args()

_,extension = os.path.splitext(args.input)

if extension==".yaml": # yaml to hdf5
  with open(args.input) as yt:
    t = parse_yaml_cgns.to_cgns_tree(yt)

    output_file = script.determine_output_file_path(args.input, args.output, ".cgns")
    C.convertPyTree2File(t,str(output_file))

elif extension==".cgns" or extension==".hdf": # hdf5 to yaml
  t = C.convertFile2PyTree(str(args.input))
  yt = parse_cgns_yaml.to_yaml(t)
  yt = '\n'.join(yt)
  output_file = script.determine_output_file_path(args.input, args.output, ".yaml")
  with open(output_file, mode='w') as f:
    f.write(yt)

else:
  raise RuntimeError('Unknown file extension "' + extension + '". The file extension must be ".yaml", ".cgns" or ".hdf"')
