#!/usr/bin/env python3

import argparse
from pathlib import Path
import sys
import numpy as np

import maia
from maia.pytree import compare as CP
from maia.pytree.compare_arrays import field_comparison, tensor_field_comparison

from mpi4py import MPI
comm = MPI.COMM_WORLD

parser = argparse.ArgumentParser(description='Diff between two CGNS files')
parser.add_argument('file0', metavar='IN', type=Path, help='first input file')
parser.add_argument('file1', metavar='IN', type=Path, help='second input file')
parser.add_argument('--tol', help='tolerance')
parser.add_argument('--tensor', help='Tensor comparison of fields', action="store_true")
args = parser.parse_args()

dist_tree_0 = maia.io.file_to_dist_tree(args.file0, comm)
dist_tree_1 = maia.io.file_to_dist_tree(args.file1, comm)

if args.tensor:
  comparison = tensor_field_comparison
else:
  comparison = field_comparison
is_ok, error_report, warning_report = CP.diff_tree(dist_tree_0, dist_tree_1, comp = comparison(np.float64(args.tol), comm))
print('=========== Differences ===========\n'+error_report)
if len(warning_report) > 0:
  print('========== Differences within tolerance ==========\n'+warning_report)
if not is_ok:
  sys.exit(1)
